import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Frank_Ruhl_Libre } from "next/font/google";

const frank = Frank_Ruhl_Libre({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-frank",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${frank.variable} antialiased`}
      >
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}


{/* <link
  href="https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre&display=swap"
  rel="stylesheet"
/>;
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Frank_Ruhl_Libre } from "next/font/google";
import LoadingSpinner from "@/components/LoadingSpinner";
import Header from "@/components/layout/Header";
import TopBar from "@/components/layout/TopBar";
import Footer from "@/components/layout/Footer";

const frank = Frank_Ruhl_Libre({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust weights as needed
  variable: "--font-frank",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${frank.variable} antialiased`}
      >
        <TopBar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
} */}
