import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import { Frank_Ruhl_Libre } from "next/font/google";
import { Toaster } from "sonner";
import { WishlistProvider } from "@/forntend/context/WishlistContext";
import { AddToCartProvider } from "@/forntend/context/AddToCartContext";
import "./globals.css";
import { ShopByCallectionProvider } from "@/forntend/context/ShopBycallection";
import AOSProvider from "@/forntend/common/AOSProvider";
import ClientMiddleware from "@/components/ProtectedRoute";

const frank = Frank_Ruhl_Libre({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-frank",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "icons/logo.svg",
  },
};

// AOS.init({ duration: 1000, once: true });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WishlistProvider>
        <AddToCartProvider>
          <ShopByCallectionProvider>
            <AOSProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} ${frank.variable} antialiased`}
              >
                <ClientMiddleware>
                  <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
                  <Toaster position="bottom-right" richColors />
                </ClientMiddleware>
              </body>
            </AOSProvider>
          </ShopByCallectionProvider>
        </AddToCartProvider>
      </WishlistProvider>
    </html>
  );
}
